### ISSUE TITLE
Download speed Indicator

### ISSUE THREAD

**Issue by sakshatshinde** [jonathanTIE/googledrive-copy-downloader#3]
Would be great if you added a way for us to see the current download speed.

**Comment by sakshatshinde** [comment]
You could use : time.clock() - start
[Check here for an example](https://stackoverflow.com/questions/40126334/get-the-speed-of-downloading-a-file-using-python)

**Comment by jonathanTIE** [comment]
The problem is that currently, it uses a downloader from the google api, the best performance that I got where with 100MB chunksize, so the loop is only updated every 100MB downloaded which won't give an accurate download speed. I could either rework it or multithread the script but I don't think it's worth the effort.

**Comment by jonathanTIE** [comment]
Feature added but it isn't updated in real-time, it displays the mean speed.
